module.exports = {
    branches: ['main'],
    plugins: [
        [
            '@semantic-release/commit-analyzer',
            {
                preset: 'angular',
                releaseRules: [
                    { type: 'feat', release: 'minor' },
                    { type: 'fix', release: 'patch' },
                    { type: 'docs', release: 'patch' },
                    { type: 'style', release: 'patch' },
                    { type: 'refactor', release: 'patch' },
                    { type: 'perf', release: 'patch' },
                    { type: 'test', release: 'patch' },
                    { type: 'build', release: 'patch' },
                    { type: 'ci', release: 'patch' },
                    { type: 'chore', release: 'patch' },
                    // Handle emoji prefixed commits
                    { message: '*feat:*', release: 'minor' },
                    { message: '*fix:*', release: 'patch' },
                    { message: '*docs:*', release: 'patch' },
                    { message: '*style:*', release: 'patch' },
                    { message: '*refactor:*', release: 'patch' },
                    { message: '*perf:*', release: 'patch' },
                    { message: '*test:*', release: 'patch' },
                    { message: '*build:*', release: 'patch' },
                    { message: '*ci:*', release: 'patch' },
                    { message: '*chore:*', release: 'patch' },
                    // Specific emoji patterns
                    { message: '*🚀*', release: 'minor' },
                    { message: '*:rocket:*', release: 'minor' },
                    { message: '*🐛*', release: 'patch' },
                    { message: '*:bug:*', release: 'patch' },
                    { message: '*📝*', release: 'patch' },
                    { message: '*:memo:*', release: 'patch' },
                    { message: '*🔧*', release: 'patch' },
                    { message: '*:wrench:*', release: 'patch' },
                    { message: '*✅*', release: 'patch' },
                    { message: '*:white_check_mark:*', release: 'patch' },
                    { message: '*🔨*', release: 'patch' },
                    { message: '*:hammer:*', release: 'patch' },
                    { scope: 'no-release', release: false },
                ],
                parserOpts: {
                    noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES'],
                },
            },
        ],
        '@semantic-release/release-notes-generator',
        '@semantic-release/npm',
        '@semantic-release/github',
    ],
};
